/** Strings of the v2 shell, bar, chat tab, dock and side-view frame. */
export default {
  en: {
    "settings.interface": "Interface",
    "settings.interfaceHint":
      "Simple: each session has Chat, Status, Workspace, Debug and Settings, with extras in a floating dock. Classic: arrange panels and presets yourself.",
    "settings.interface.v1": "Classic",
    "settings.interface.v2": "Simple",
    "tabs.label": "Session tabs",
    "tab.chat": "Chat",
    "tab.status": "Status",
    "tab.workspace": "Workspace",
    "tab.debug": "Debug",
    "tab.settings": "Settings",
    privileged: "Privileged node",
    stop: "Stop session",
    close: "Close",
    loading: "Loading…",
    "hero.title": "What should {name} work on?",
    "hero.anyone": "the team",
    "hero.channel": "Post to #{name}",
    "hero.hint": "Enter to send · Shift+Enter for a new line · / for commands",
    "transcript.partial": "Loaded history — usage figures are partial",
    "transcript.newer": "Newer messages are waiting — refresh",
    "transcript.reset": "History changed — reload",
    "transcript.historyFailed": "Could not load history: {error}",
    "chat.dropHint": "Drop files to attach",
    "composer.remove": "Remove {name}",
    "composer.noTab": "Pick a conversation before sending.",
    "composer.notConnected": "Not connected to the session.",
    "composer.commandFailed": "Command failed: {error}",
    "composer.compactFailed": "Compact failed: {error}",
    "composer.clearFailed": "Clear failed: {error}",
    "composer.cancelEdit": "Cancel",
    "composer.pendingShow": "Show",
    "composer.modelChannel":
      "A channel has no model of its own — open a creature's chat to switch it.",
    "composer.context": "Context {used} of {max} tokens ({pct}%)",
    "composer.contextCompact": "compacts at {pct}%",
    "dock.more": "More",
    "dock.collapse": "Collapse dock",
    "dock.expand": "Open dock",
    "dock.pin": "Pin to side view",
    "side.close": "Close side view",
    "side.unpin": "Back to floating",
    "rail.agents": "Agents",
    "rail.channels": "Channels",
    "rail.collapse": "Collapse list",
    "rail.expand": "Show agents and channels",
    "members.title": "Members",
    "members.show": "Show channel members",
    "members.hide": "Hide members",
    "members.empty": "No creature posts to or listens on this channel.",
    "members.running": "Running",
    "members.stopped": "Stopped",
    "members.sends": "posts",
    "members.listens": "listens",
    "members.both": "posts · listens",
    "members.openChat": "Chat with {name}",
  },
  "zh-TW": {
    "settings.interface": "介面",
    "settings.interfaceHint":
      "簡潔：每個工作階段有聊天、狀態、工作區、除錯與設定，其餘功能收在浮動面板。經典：自行安排面板與預設配置。",
    "settings.interface.v1": "經典",
    "settings.interface.v2": "簡潔",
    "tabs.label": "工作階段分頁",
    "tab.chat": "聊天",
    "tab.status": "狀態",
    "tab.workspace": "工作區",
    "tab.debug": "除錯",
    "tab.settings": "設定",
    privileged: "特權節點",
    stop: "停止工作階段",
    close: "關閉",
    loading: "載入中…",
    "hero.title": "要讓 {name} 做什麼？",
    "hero.anyone": "團隊",
    "hero.channel": "發送到 #{name}",
    "hero.hint": "Enter 送出 · Shift+Enter 換行 · / 指令",
    "transcript.partial": "已載入的歷史 — 用量統計不完整",
    "transcript.newer": "有較新的訊息 — 重新整理",
    "transcript.reset": "歷史已變更 — 重新載入",
    "transcript.historyFailed": "無法載入歷史：{error}",
    "chat.dropHint": "放開以附加檔案",
    "composer.remove": "移除 {name}",
    "composer.noTab": "請先選擇對話再送出。",
    "composer.notConnected": "尚未連線到工作階段。",
    "composer.commandFailed": "指令失敗：{error}",
    "composer.compactFailed": "壓縮失敗：{error}",
    "composer.clearFailed": "清除失敗：{error}",
    "composer.cancelEdit": "取消",
    "composer.pendingShow": "檢視",
    "composer.modelChannel": "頻道沒有自己的模型——開啟某個生物的對話來切換。",
    "composer.context": "上下文 {used} / {max} tokens（{pct}%）",
    "composer.contextCompact": "於 {pct}% 時壓縮",
    "dock.more": "更多",
    "dock.collapse": "收合浮動面板",
    "dock.expand": "開啟浮動面板",
    "dock.pin": "固定到側邊",
    "side.close": "關閉側邊",
    "side.unpin": "改回浮動",
    "rail.agents": "代理",
    "rail.channels": "頻道",
    "rail.collapse": "收合清單",
    "rail.expand": "顯示代理與頻道",
    "members.title": "成員",
    "members.show": "顯示頻道成員",
    "members.hide": "隱藏成員",
    "members.empty": "沒有生物在此頻道發送或收聽。",
    "members.running": "執行中",
    "members.stopped": "已停止",
    "members.sends": "發送",
    "members.listens": "收聽",
    "members.both": "發送 · 收聽",
    "members.openChat": "與 {name} 對話",
  },
  "zh-CN": {
    "settings.interface": "界面",
    "settings.interfaceHint":
      "简洁：每个会话有聊天、状态、工作区、调试与设置，其余功能收在浮动面板。经典：自行安排面板与预设布局。",
    "settings.interface.v1": "经典",
    "settings.interface.v2": "简洁",
    "tabs.label": "会话分页",
    "tab.chat": "聊天",
    "tab.status": "状态",
    "tab.workspace": "工作区",
    "tab.debug": "调试",
    "tab.settings": "设置",
    privileged: "特权节点",
    stop: "停止会话",
    close: "关闭",
    loading: "加载中…",
    "hero.title": "要让 {name} 做什么？",
    "hero.anyone": "团队",
    "hero.channel": "发送到 #{name}",
    "hero.hint": "Enter 发送 · Shift+Enter 换行 · / 命令",
    "transcript.partial": "已加载的历史 — 用量统计不完整",
    "transcript.newer": "有较新的消息 — 刷新",
    "transcript.reset": "历史已变更 — 重新加载",
    "transcript.historyFailed": "无法加载历史：{error}",
    "chat.dropHint": "松开以附加文件",
    "composer.remove": "移除 {name}",
    "composer.noTab": "请先选择对话再发送。",
    "composer.notConnected": "尚未连接到会话。",
    "composer.commandFailed": "命令失败：{error}",
    "composer.compactFailed": "压缩失败：{error}",
    "composer.clearFailed": "清除失败：{error}",
    "composer.cancelEdit": "取消",
    "composer.pendingShow": "查看",
    "composer.modelChannel": "频道没有自己的模型——打开某个生物的对话来切换。",
    "composer.context": "上下文 {used} / {max} tokens（{pct}%）",
    "composer.contextCompact": "于 {pct}% 时压缩",
    "dock.more": "更多",
    "dock.collapse": "收起浮动面板",
    "dock.expand": "打开浮动面板",
    "dock.pin": "固定到侧边",
    "side.close": "关闭侧边",
    "side.unpin": "改回浮动",
    "rail.agents": "代理",
    "rail.channels": "频道",
    "rail.collapse": "收起列表",
    "rail.expand": "显示代理与频道",
    "members.title": "成员",
    "members.show": "显示频道成员",
    "members.hide": "隐藏成员",
    "members.empty": "没有 Creature 在此频道发送或收听。",
    "members.running": "运行中",
    "members.stopped": "已停止",
    "members.sends": "发送",
    "members.listens": "收听",
    "members.both": "发送 · 收听",
    "members.openChat": "与 {name} 对话",
  },
}
