/** Strings of the Debug tab. */
export default {
  en: {
    "debug.events": "Events",
    "debug.logs": "Logs",
    "debug.prompt": "Prompt",
    "debug.trace": "Trace",
    "debug.filter": "Filter…",
    "debug.allKinds": "All kinds",
    "debug.pause": "Pause",
    "debug.resume": "Resume",
    "debug.paused": "paused",
    "debug.download": "Download",
    "debug.clear": "Clear",
    "debug.count": "{shown} of {total}",
    "debug.empty": "Nothing matches",
    "debug.none.events": "No messages in this session yet.",
    "debug.none.logs": "No log lines yet.",
    "debug.none.trace": "No tool or sub-agent calls in this conversation yet.",
    "debug.selectRow": "Select a row to see its details",
    "debug.copy": "Copy",
    "debug.refresh": "Refresh",
    "debug.diff": "Diff with previous",
    "debug.target": "Agent",
    "debug.fetchedAt": "fetched {time}",
    "debug.promptUnavailable":
      "Pick an agent conversation (not a channel) to see its system prompt.",
    "debug.connected": "connected",
    "debug.connecting": "connecting…",
    "debug.traceScope": "Tool and sub-agent calls of {name}",
  },
  "zh-TW": {
    "debug.events": "事件",
    "debug.logs": "日誌",
    "debug.prompt": "提示詞",
    "debug.trace": "追蹤",
    "debug.filter": "篩選…",
    "debug.allKinds": "全部類型",
    "debug.pause": "暫停",
    "debug.resume": "繼續",
    "debug.paused": "已暫停",
    "debug.download": "下載",
    "debug.clear": "清除",
    "debug.count": "{shown} / {total}",
    "debug.empty": "沒有符合的項目",
    "debug.none.events": "此工作階段尚無訊息。",
    "debug.none.logs": "尚無日誌。",
    "debug.none.trace": "此對話尚無工具或子代理呼叫。",
    "debug.selectRow": "選擇一列以查看詳細內容",
    "debug.copy": "複製",
    "debug.refresh": "重新整理",
    "debug.diff": "與上次比較",
    "debug.target": "代理",
    "debug.fetchedAt": "取得於 {time}",
    "debug.promptUnavailable": "選擇一個代理對話（非頻道）以查看其系統提示詞。",
    "debug.connected": "已連線",
    "debug.connecting": "連線中…",
    "debug.traceScope": "{name} 的工具與子代理呼叫",
  },
  "zh-CN": {
    "debug.events": "事件",
    "debug.logs": "日志",
    "debug.prompt": "提示词",
    "debug.trace": "追踪",
    "debug.filter": "筛选…",
    "debug.allKinds": "全部类型",
    "debug.pause": "暂停",
    "debug.resume": "继续",
    "debug.paused": "已暂停",
    "debug.download": "下载",
    "debug.clear": "清除",
    "debug.count": "{shown} / {total}",
    "debug.empty": "没有匹配的项目",
    "debug.none.events": "此会话暂无消息。",
    "debug.none.logs": "暂无日志。",
    "debug.none.trace": "此对话暂无工具或子代理调用。",
    "debug.selectRow": "选择一行以查看详细内容",
    "debug.copy": "复制",
    "debug.refresh": "刷新",
    "debug.diff": "与上次比较",
    "debug.target": "代理",
    "debug.fetchedAt": "获取于 {time}",
    "debug.promptUnavailable": "选择一个代理对话（非频道）以查看其系统提示词。",
    "debug.connected": "已连接",
    "debug.connecting": "连接中…",
    "debug.traceScope": "{name} 的工具与子代理调用",
  },
}
