/** Strings of the phone session layout: header, sheets, menus and pages. */
export default {
  en: {
    "phone.back": "Back",
    "phone.menu": "Session menu",
    "phone.conversations": "Conversations",
    "phone.switchConversation": "Switch conversation",
    "phone.agents": "Agents",
    "phone.channels": "Channels",
    "phone.addCreature": "Add creature",
    "phone.addChannel": "Add channel",
    "phone.session": "Session",
    "phone.thisConversation": "This conversation",
    "phone.tools": "Tools",
    "phone.compact": "Compact context",
    "phone.clear": "Clear context",
    "phone.stop": "Stop session",
    "phone.noModel": "No model",
    "phone.pickModel": "Model",
    "phone.modelFor": "Model for {name}",
    "phone.modelTitle": "Switch model",
    "phone.modelHint": "The model each creature in this session runs on. Tap one to switch it.",
    "phone.agent": "Agent",
    "phone.pickAgent": "Pick an agent…",
    "phone.search": "Search models or providers",
    "phone.refresh": "Refresh",
    "phone.models": "Models",
    "phone.variations": "Variations",
    "phone.default": "default",
    "phone.current": "current",
    "phone.noModels": "No matching models.",
    "phone.loadingModels": "Loading models…",
    "phone.switch": "Switch",
    "phone.switching": "Switching…",
    "phone.switched": "Switched {name} to {model}",
    "phone.switchFailed": "Model switch failed: {error}",
    "phone.model": "Model",
    "phone.tokens": "Tokens",
    "phone.job": "Job",
    "phone.status": "Status",
  },
  "zh-TW": {
    "phone.back": "返回",
    "phone.menu": "工作階段選單",
    "phone.conversations": "對話",
    "phone.switchConversation": "切換對話",
    "phone.agents": "代理",
    "phone.channels": "頻道",
    "phone.addCreature": "新增生物",
    "phone.addChannel": "新增頻道",
    "phone.session": "工作階段",
    "phone.thisConversation": "目前對話",
    "phone.tools": "工具",
    "phone.compact": "壓縮上下文",
    "phone.clear": "清除上下文",
    "phone.stop": "停止工作階段",
    "phone.noModel": "沒有模型",
    "phone.pickModel": "模型",
    "phone.modelFor": "{name} 的模型",
    "phone.modelTitle": "切換模型",
    "phone.modelHint": "此工作階段中每個生物使用的模型。點一下即可切換。",
    "phone.agent": "代理",
    "phone.pickAgent": "選擇代理…",
    "phone.search": "搜尋模型或供應商",
    "phone.refresh": "重新整理",
    "phone.models": "模型",
    "phone.variations": "變體",
    "phone.default": "預設",
    "phone.current": "目前",
    "phone.noModels": "沒有符合的模型。",
    "phone.loadingModels": "正在載入模型…",
    "phone.switch": "切換",
    "phone.switching": "切換中…",
    "phone.switched": "已將 {name} 切換為 {model}",
    "phone.switchFailed": "切換模型失敗：{error}",
    "phone.model": "模型",
    "phone.tokens": "Tokens",
    "phone.job": "工作",
    "phone.status": "狀態",
  },
  "zh-CN": {
    "phone.back": "返回",
    "phone.menu": "会话菜单",
    "phone.conversations": "对话",
    "phone.switchConversation": "切换对话",
    "phone.agents": "代理",
    "phone.channels": "频道",
    "phone.addCreature": "添加 Creature",
    "phone.addChannel": "添加频道",
    "phone.session": "会话",
    "phone.thisConversation": "当前对话",
    "phone.tools": "工具",
    "phone.compact": "压缩上下文",
    "phone.clear": "清除上下文",
    "phone.stop": "停止会话",
    "phone.noModel": "没有模型",
    "phone.pickModel": "模型",
    "phone.modelFor": "{name} 的模型",
    "phone.modelTitle": "切换模型",
    "phone.modelHint": "此会话中每个 Creature 使用的模型。点一下即可切换。",
    "phone.agent": "代理",
    "phone.pickAgent": "选择代理…",
    "phone.search": "搜索模型或提供方",
    "phone.refresh": "刷新",
    "phone.models": "模型",
    "phone.variations": "变体",
    "phone.default": "默认",
    "phone.current": "当前",
    "phone.noModels": "没有匹配的模型。",
    "phone.loadingModels": "正在加载模型…",
    "phone.switch": "切换",
    "phone.switching": "切换中…",
    "phone.switched": "已将 {name} 切换为 {model}",
    "phone.switchFailed": "切换模型失败：{error}",
    "phone.model": "模型",
    "phone.tokens": "Tokens",
    "phone.job": "任务",
    "phone.status": "状态",
  },
}
