/** Strings of the Settings tab. */
export default {
  en: {
    "set.nav": "Settings sections",
    "set.creature": "Creature",
    "set.pending": "{n} unsaved change(s)",
    "set.reset": "Reset",
    "set.saving": "Saving…",
    "set.apply": "Apply",
    "set.filter": "Filter…",
    "set.refresh": "Refresh",
    "set.noMatches": "No matches",
    "set.model.title": "Model",
    "set.model.hint":
      "The model each creature in this session runs on. Pick new ones and apply them together.",
    "set.model.creature": "Creature",
    "set.model.current": "Current",
    "set.model.switchTo": "Model",
    "set.model.context": "Context",
    "set.model.pick": "Pick a model",
    "set.model.switched": "Switched {n} creature(s).",
    "set.env.title": "Environment",
    "set.env.hint": "The working directory and environment variables a creature's tools see.",
    "set.env.pwd": "Working directory",
    "set.env.vars": "Variables ({n})",
    "set.env.secrets":
      "Credential-like keys (secret, token, key, password, …) are removed by the server before they reach this page.",
    "set.triggers.title": "Triggers",
    "set.triggers.hint": "Timers, events and conditions that wake a creature without a message.",
    "set.triggers.empty": "No active triggers.",
    "set.triggers.type": "Type",
    "set.triggers.id": "Id",
    "set.triggers.state": "State",
    "set.triggers.created": "Created",
    "set.triggers.running": "running",
    "set.triggers.idle": "waiting",
    "set.cost.title": "Cost",
    "set.cost.hint":
      "Tokens spent per conversation, with an estimate where the model's price is known.",
    "set.cost.conversation": "Conversation",
    "set.cost.model": "Model",
    "set.cost.in": "Input tokens",
    "set.cost.out": "Output tokens",
    "set.cost.cached": "Cached",
    "set.cost.estimate": "Estimated cost",
    "set.cost.empty": "No tokens spent yet.",
    "set.cost.note":
      "Token totals include sub-agent usage; the cost estimate covers the conversations listed. Cached input is billed at the cache rate; models without a list price are skipped.",
    "set.workspace.title": "Workspace",
    "set.workspace.hint":
      "The directory a creature's tools (read, glob, grep, edit, bash) work in. Sub-agents follow the change.",
    "set.workspace.current": "Current directory",
    "set.workspace.next": "New directory",
    "set.workspace.pathHint": "Absolute path; ~ is expanded on the server.",
    "set.workspace.busy":
      "The creature is working — interrupt its turn before switching directory.",
    "set.workspace.switch": "Switch",
    "set.workspace.switched": "Switched to {path}",
    "set.extensions.title": "Extensions",
    "set.extensions.hint":
      "Packages installed on this host: creatures, terrariums, tools and plugins.",
    "set.extensions.empty": "No packages installed.",
  },
  "zh-TW": {
    "set.nav": "設定分類",
    "set.creature": "生物",
    "set.pending": "{n} 項未儲存的變更",
    "set.reset": "重設",
    "set.saving": "儲存中…",
    "set.apply": "套用",
    "set.filter": "篩選…",
    "set.refresh": "重新整理",
    "set.noMatches": "沒有符合的項目",
    "set.model.title": "模型",
    "set.model.hint": "此工作階段中每個生物使用的模型。選好後一起套用。",
    "set.model.creature": "生物",
    "set.model.current": "目前",
    "set.model.switchTo": "模型",
    "set.model.context": "上下文",
    "set.model.pick": "選擇模型",
    "set.model.switched": "已切換 {n} 個生物。",
    "set.env.title": "環境",
    "set.env.hint": "生物的工具所看到的工作目錄與環境變數。",
    "set.env.pwd": "工作目錄",
    "set.env.vars": "變數（{n}）",
    "set.env.secrets": "類似憑證的鍵（secret、token、key、password…）在送達此頁前已由伺服器移除。",
    "set.triggers.title": "觸發器",
    "set.triggers.hint": "不需訊息即可喚醒生物的計時器、事件與條件。",
    "set.triggers.empty": "沒有啟用中的觸發器。",
    "set.triggers.type": "類型",
    "set.triggers.id": "ID",
    "set.triggers.state": "狀態",
    "set.triggers.created": "建立時間",
    "set.triggers.running": "執行中",
    "set.triggers.idle": "等待中",
    "set.cost.title": "費用",
    "set.cost.hint": "每個對話花費的權杖，並在已知模型價格時估算費用。",
    "set.cost.conversation": "對話",
    "set.cost.model": "模型",
    "set.cost.in": "輸入權杖",
    "set.cost.out": "輸出權杖",
    "set.cost.cached": "快取",
    "set.cost.estimate": "估計費用",
    "set.cost.empty": "尚未花費任何權杖。",
    "set.cost.note":
      "權杖總計包含子代理用量；費用估算只涵蓋列出的對話。快取輸入以快取價格計算；沒有公開價格的模型不計入。",
    "set.workspace.title": "工作區",
    "set.workspace.hint":
      "生物的工具（read、glob、grep、edit、bash）所操作的目錄。子代理會跟著切換。",
    "set.workspace.current": "目前目錄",
    "set.workspace.next": "新目錄",
    "set.workspace.pathHint": "絕對路徑；~ 會在伺服器端展開。",
    "set.workspace.busy": "生物正在工作 — 請先中斷其回合再切換目錄。",
    "set.workspace.switch": "切換",
    "set.workspace.switched": "已切換到 {path}",
    "set.extensions.title": "擴充",
    "set.extensions.hint": "此主機已安裝的套件：生物、Terrarium、工具與外掛。",
    "set.extensions.empty": "尚未安裝任何套件。",
  },
  "zh-CN": {
    "set.nav": "设置分类",
    "set.creature": "Creature",
    "set.pending": "{n} 项未保存的更改",
    "set.reset": "重置",
    "set.saving": "保存中…",
    "set.apply": "应用",
    "set.filter": "筛选…",
    "set.refresh": "刷新",
    "set.noMatches": "没有匹配的项目",
    "set.model.title": "模型",
    "set.model.hint": "此会话中每个 Creature 使用的模型。选好后一起应用。",
    "set.model.creature": "Creature",
    "set.model.current": "当前",
    "set.model.switchTo": "模型",
    "set.model.context": "上下文",
    "set.model.pick": "选择模型",
    "set.model.switched": "已切换 {n} 个 Creature。",
    "set.env.title": "环境",
    "set.env.hint": "Creature 的工具所看到的工作目录与环境变量。",
    "set.env.pwd": "工作目录",
    "set.env.vars": "变量（{n}）",
    "set.env.secrets": "类似凭证的键（secret、token、key、password…）在到达此页前已由服务器移除。",
    "set.triggers.title": "触发器",
    "set.triggers.hint": "无需消息即可唤醒 Creature 的定时器、事件与条件。",
    "set.triggers.empty": "没有启用中的触发器。",
    "set.triggers.type": "类型",
    "set.triggers.id": "ID",
    "set.triggers.state": "状态",
    "set.triggers.created": "创建时间",
    "set.triggers.running": "运行中",
    "set.triggers.idle": "等待中",
    "set.cost.title": "费用",
    "set.cost.hint": "每个对话花费的令牌，并在已知模型价格时估算费用。",
    "set.cost.conversation": "对话",
    "set.cost.model": "模型",
    "set.cost.in": "输入令牌",
    "set.cost.out": "输出令牌",
    "set.cost.cached": "缓存",
    "set.cost.estimate": "估计费用",
    "set.cost.empty": "尚未花费任何令牌。",
    "set.cost.note":
      "令牌总计包含子代理用量；费用估算只涵盖列出的对话。缓存输入以缓存价格计算；没有公开价格的模型不计入。",
    "set.workspace.title": "工作区",
    "set.workspace.hint":
      "Creature 的工具（read、glob、grep、edit、bash）所操作的目录。子代理会跟着切换。",
    "set.workspace.current": "当前目录",
    "set.workspace.next": "新目录",
    "set.workspace.pathHint": "绝对路径；~ 会在服务器端展开。",
    "set.workspace.busy": "Creature 正在工作 — 请先中断其回合再切换目录。",
    "set.workspace.switch": "切换",
    "set.workspace.switched": "已切换到 {path}",
    "set.extensions.title": "扩展",
    "set.extensions.hint": "此主机已安装的包：Creature、Terrarium、工具与插件。",
    "set.extensions.empty": "尚未安装任何包。",
  },
}
