/** Strings of the side-view contents. */
export default {
  en: {
    "side.canvas.title": "Canvas",
    "side.subagent.title": "Sub-agent",
    "side.peek.title": "Conversation",
    "side.drive.title": "Drive",
    "side.terminal.title": "Terminal",
    "side.graph.title": "Graph",
    "side.widget.title": "Widget",
    "side.canvas.empty":
      "No artifacts yet. Images, long code blocks and file previews appear here.",
    "side.canvas.copy": "Copy",
    "side.canvas.download": "Download",
    "side.canvas.remove": "Remove from canvas",
    "side.canvas.lines": "{n} lines",
    "side.subagent.loading": "Loading the sub-agent's conversation…",
    "side.subagent.unavailable": "This sub-agent's conversation is not available.",
    "side.subagent.empty": "The sub-agent has not said anything yet.",
    "side.subagent.system": "system prompt ({n} chars)",
    "side.subagent.live": "live",
    "side.subagent.user": "task",
    "side.peek.empty": "No messages in this conversation yet.",
    "side.peek.notOpen": "This conversation is not loaded yet.",
    "side.peek.open": "Open in chat",
    "side.peek.earlier": "{n} earlier messages",
    "side.drive.missing": "This drive is no longer in the session.",
    "side.drive.loading": "Loading drive…",
    "side.terminal.connect": "Connect",
    "side.terminal.disconnected": "disconnected",
    "side.terminal.none": "No creature to open a terminal in.",
    "side.terminal.state.open": "connected",
    "side.terminal.state.connecting": "connecting…",
    "side.terminal.state.closed": "disconnected",
    "side.graph.none": "No session graph.",
  },
  "zh-TW": {
    "side.canvas.title": "畫布",
    "side.subagent.title": "子代理",
    "side.peek.title": "對話",
    "side.drive.title": "驅動",
    "side.terminal.title": "終端機",
    "side.graph.title": "圖",
    "side.widget.title": "小工具",
    "side.canvas.empty": "尚無成果。圖片、長程式碼區塊與檔案預覽會出現在這裡。",
    "side.canvas.copy": "複製",
    "side.canvas.download": "下載",
    "side.canvas.remove": "從畫布移除",
    "side.canvas.lines": "{n} 行",
    "side.subagent.loading": "正在載入子代理的對話…",
    "side.subagent.unavailable": "無法取得此子代理的對話。",
    "side.subagent.empty": "子代理還沒有說任何話。",
    "side.subagent.system": "系統提示（{n} 字元）",
    "side.subagent.live": "即時",
    "side.subagent.user": "任務",
    "side.peek.empty": "此對話尚無訊息。",
    "side.peek.notOpen": "此對話尚未載入。",
    "side.peek.open": "在聊天中開啟",
    "side.peek.earlier": "更早的 {n} 則訊息",
    "side.drive.missing": "此驅動已不在工作階段中。",
    "side.drive.loading": "正在載入驅動…",
    "side.terminal.connect": "連線",
    "side.terminal.disconnected": "已中斷",
    "side.terminal.none": "沒有可開啟終端機的生物。",
    "side.terminal.state.open": "已連線",
    "side.terminal.state.connecting": "連線中…",
    "side.terminal.state.closed": "已中斷",
    "side.graph.none": "沒有工作階段圖。",
  },
  "zh-CN": {
    "side.canvas.title": "画布",
    "side.subagent.title": "子代理",
    "side.peek.title": "对话",
    "side.drive.title": "驱动",
    "side.terminal.title": "终端",
    "side.graph.title": "图",
    "side.widget.title": "小组件",
    "side.canvas.empty": "暂无成果。图片、长代码块与文件预览会出现在这里。",
    "side.canvas.copy": "复制",
    "side.canvas.download": "下载",
    "side.canvas.remove": "从画布移除",
    "side.canvas.lines": "{n} 行",
    "side.subagent.loading": "正在加载子代理的对话…",
    "side.subagent.unavailable": "无法获取此子代理的对话。",
    "side.subagent.empty": "子代理还没有说任何话。",
    "side.subagent.system": "系统提示（{n} 字符）",
    "side.subagent.live": "实时",
    "side.subagent.user": "任务",
    "side.peek.empty": "此对话暂无消息。",
    "side.peek.notOpen": "此对话尚未加载。",
    "side.peek.open": "在聊天中打开",
    "side.peek.earlier": "更早的 {n} 条消息",
    "side.drive.missing": "此驱动已不在会话中。",
    "side.drive.loading": "正在加载驱动…",
    "side.terminal.connect": "连接",
    "side.terminal.disconnected": "已断开",
    "side.terminal.none": "没有可打开终端的 Creature。",
    "side.terminal.state.open": "已连接",
    "side.terminal.state.connecting": "连接中…",
    "side.terminal.state.closed": "已断开",
    "side.graph.none": "没有会话图。",
  },
}
