/** Strings of the Status tab. */
export default {
  en: {
    "status.session": "Session",
    "status.usage": "Usage",
    "status.health": "Health",
    "status.state.running": "running",
    "status.state.stopped": "stopped",
    "status.stopFailed": "Could not stop {name}: {error}",
    "status.uptime": "Uptime",
    "status.site": "Site",
    "status.model": "Model",
    "status.provider": "Provider",
    "status.sessionId": "Session id",
    "status.promptIn": "Prompt in",
    "status.completion": "Completion",
    "status.cached": "Cached",
    "status.total": "Total",
    "status.compactAt": "compacts at {pct}%",
    "status.sessionScope": "Whole session",
    "status.contextPerAgent": "Context per agent",
    "status.contextOf": "Context of {name}",
    "status.connection": "Connection",
    "status.recovering": "Recovering models",
    "status.unread": "Unread",
    "status.stoppedAgents": "Stopped agents",
    "status.runningJobs": "Running jobs",
    "status.agents": "Agents",
    "status.channels": "Channels",
    "status.drives": "Drives",
    "status.jobs": "Running jobs",
    "status.col.name": "Name",
    "status.col.status": "Status",
    "status.col.model": "Model",
    "status.col.tokens": "Tokens",
    "status.col.job": "Current job",
    "status.col.senders": "Senders",
    "status.col.listeners": "Listeners",
    "status.col.title": "Title",
    "status.col.kind": "Kind",
    "status.col.assignee": "Assignee",
    "status.col.owner": "Owner",
    "status.col.creature": "Agent",
    "status.col.elapsed": "Elapsed",
    "status.start": "Start",
    "status.stop": "Stop",
    "status.openChat": "Chat",
    "status.unassigned": "unassigned",
    "status.cancelling": "cancelling…",
    "status.none.agents": "No agents",
    "status.none.channels": "No channels",
    "status.none.drives": "No drives",
    "status.none.jobs": "No running jobs",
    "status.selectModel": "Select model",
  },
  "zh-TW": {
    "status.session": "工作階段",
    "status.usage": "用量",
    "status.health": "健康狀態",
    "status.state.running": "執行中",
    "status.state.stopped": "已停止",
    "status.stopFailed": "無法停止 {name}：{error}",
    "status.uptime": "執行時間",
    "status.site": "站點",
    "status.model": "模型",
    "status.provider": "提供者",
    "status.sessionId": "工作階段 ID",
    "status.promptIn": "輸入",
    "status.completion": "輸出",
    "status.cached": "快取",
    "status.total": "總計",
    "status.compactAt": "於 {pct}% 時壓縮",
    "status.sessionScope": "整個工作階段",
    "status.contextPerAgent": "各代理的上下文",
    "status.contextOf": "{name} 的上下文",
    "status.connection": "連線",
    "status.recovering": "模型恢復中",
    "status.unread": "未讀",
    "status.stoppedAgents": "已停止的代理",
    "status.runningJobs": "執行中的工作",
    "status.agents": "代理",
    "status.channels": "頻道",
    "status.drives": "驅動",
    "status.jobs": "執行中的工作",
    "status.col.name": "名稱",
    "status.col.status": "狀態",
    "status.col.model": "模型",
    "status.col.tokens": "權杖",
    "status.col.job": "目前工作",
    "status.col.senders": "發送者",
    "status.col.listeners": "收聽者",
    "status.col.title": "標題",
    "status.col.kind": "類型",
    "status.col.assignee": "負責者",
    "status.col.owner": "擁有者",
    "status.col.creature": "代理",
    "status.col.elapsed": "已用時間",
    "status.start": "啟動",
    "status.stop": "停止",
    "status.openChat": "聊天",
    "status.unassigned": "未指派",
    "status.cancelling": "取消中…",
    "status.none.agents": "沒有代理",
    "status.none.channels": "沒有頻道",
    "status.none.drives": "沒有驅動",
    "status.none.jobs": "沒有執行中的工作",
    "status.selectModel": "選擇模型",
  },
  "zh-CN": {
    "status.session": "会话",
    "status.usage": "用量",
    "status.health": "健康状态",
    "status.state.running": "运行中",
    "status.state.stopped": "已停止",
    "status.stopFailed": "无法停止 {name}：{error}",
    "status.uptime": "运行时间",
    "status.site": "站点",
    "status.model": "模型",
    "status.provider": "提供方",
    "status.sessionId": "会话 ID",
    "status.promptIn": "输入",
    "status.completion": "输出",
    "status.cached": "缓存",
    "status.total": "总计",
    "status.compactAt": "于 {pct}% 时压缩",
    "status.sessionScope": "整个会话",
    "status.contextPerAgent": "各代理的上下文",
    "status.contextOf": "{name} 的上下文",
    "status.connection": "连接",
    "status.recovering": "模型恢复中",
    "status.unread": "未读",
    "status.stoppedAgents": "已停止的代理",
    "status.runningJobs": "运行中的任务",
    "status.agents": "代理",
    "status.channels": "频道",
    "status.drives": "驱动",
    "status.jobs": "运行中的任务",
    "status.col.name": "名称",
    "status.col.status": "状态",
    "status.col.model": "模型",
    "status.col.tokens": "令牌",
    "status.col.job": "当前任务",
    "status.col.senders": "发送者",
    "status.col.listeners": "收听者",
    "status.col.title": "标题",
    "status.col.kind": "类型",
    "status.col.assignee": "负责者",
    "status.col.owner": "所有者",
    "status.col.creature": "代理",
    "status.col.elapsed": "已用时间",
    "status.start": "启动",
    "status.stop": "停止",
    "status.openChat": "聊天",
    "status.unassigned": "未分配",
    "status.cancelling": "取消中…",
    "status.none.agents": "没有代理",
    "status.none.channels": "没有频道",
    "status.none.drives": "没有驱动",
    "status.none.jobs": "没有运行中的任务",
    "status.selectModel": "选择模型",
  },
}
