/** Strings of the dock widgets. */
export default {
  en: {
    "widget.agents.title": "Agents",
    "widget.channels.title": "Channels",
    "widget.drives.title": "Drives",
    "widget.jobs.title": "Jobs",
    "widget.canvas.title": "Canvas",
    "widget.scratchpad.title": "Scratchpad",
    "widget.plugins.title": "Plugins",
    "widget.search.title": "Search",
    "widget.usage.title": "Usage",
    "widget.usage.empty": "No tokens spent yet.",
    "widget.usage.subagents": "Sub-agents",
    "widget.openChat": "Open chat",
    "widget.start": "Start",
    "widget.stop": "Stop",
    "widget.busy": "Working",
    "widget.noModel": "no model",
    "widget.agents.empty": "No creatures in this session.",
    "widget.channels.empty": "No channels yet.",
    "widget.channels.members": "{n} members",
    "widget.channels.peek": "Peek beside chat",
    "widget.channels.last": "{sender}: {text}",
    "widget.drives.empty": "No drives in this session.",
    "widget.jobs.empty": "Nothing running.",
    "widget.jobs.subagent": "sub-agent",
    "widget.jobs.tool": "tool",
    "widget.jobs.cancelling": "stopping…",
    "widget.jobs.view": "View",
    "widget.canvas.empty": "No artifacts yet.",
    "widget.focus.none": "Open a creature's conversation to see its {what}.",
    "widget.scratchpad.empty": "{name} has written nothing to its scratchpad.",
    "widget.scratchpad.key": "key",
    "widget.scratchpad.value": "value",
    "widget.scratchpad.add": "Add",
    "widget.scratchpad.save": "Save",
    "widget.scratchpad.edit": "Edit",
    "widget.scratchpad.cancel": "Cancel",
    "widget.scratchpad.delete": "Delete",
    "widget.scratchpad.what": "scratchpad",
    "widget.plugins.empty": "No modules reported.",
    "widget.plugins.what": "plugins and tools",
    "widget.plugins.type.plugin": "Plugins",
    "widget.plugins.type.native_tool": "Native tools",
    "widget.plugins.type.tool": "Tools",
    "widget.plugins.type.trigger": "Triggers",
    "widget.search.placeholder": "Search this session's memory…",
    "widget.search.empty": "No matches.",
    "widget.search.hint": "Search everything the session has said and done.",
    "widget.search.mode.auto": "Auto",
    "widget.search.mode.fts": "Keyword",
    "widget.search.mode.semantic": "Semantic",
    "widget.retry": "Retry",
  },
  "zh-TW": {
    "widget.agents.title": "代理",
    "widget.channels.title": "頻道",
    "widget.drives.title": "驅動",
    "widget.jobs.title": "工作",
    "widget.canvas.title": "畫布",
    "widget.scratchpad.title": "暫存區",
    "widget.plugins.title": "外掛",
    "widget.search.title": "搜尋",
    "widget.usage.title": "用量",
    "widget.usage.empty": "尚未使用任何權杖。",
    "widget.usage.subagents": "子代理",
    "widget.openChat": "開啟對話",
    "widget.start": "啟動",
    "widget.stop": "停止",
    "widget.busy": "工作中",
    "widget.noModel": "無模型",
    "widget.agents.empty": "此工作階段沒有生物。",
    "widget.channels.empty": "尚無頻道。",
    "widget.channels.members": "{n} 位成員",
    "widget.channels.peek": "在聊天旁檢視",
    "widget.channels.last": "{sender}：{text}",
    "widget.drives.empty": "此工作階段沒有驅動。",
    "widget.jobs.empty": "目前沒有執行中的工作。",
    "widget.jobs.subagent": "子代理",
    "widget.jobs.tool": "工具",
    "widget.jobs.cancelling": "停止中…",
    "widget.jobs.view": "檢視",
    "widget.canvas.empty": "尚無成果。",
    "widget.focus.none": "開啟某個生物的對話以檢視其{what}。",
    "widget.scratchpad.empty": "{name} 的暫存區是空的。",
    "widget.scratchpad.key": "鍵",
    "widget.scratchpad.value": "值",
    "widget.scratchpad.add": "新增",
    "widget.scratchpad.save": "儲存",
    "widget.scratchpad.edit": "編輯",
    "widget.scratchpad.cancel": "取消",
    "widget.scratchpad.delete": "刪除",
    "widget.scratchpad.what": "暫存區",
    "widget.plugins.empty": "沒有回報任何模組。",
    "widget.plugins.what": "外掛與工具",
    "widget.plugins.type.plugin": "外掛",
    "widget.plugins.type.native_tool": "原生工具",
    "widget.plugins.type.tool": "工具",
    "widget.plugins.type.trigger": "觸發器",
    "widget.search.placeholder": "搜尋此工作階段的記憶…",
    "widget.search.empty": "沒有符合的結果。",
    "widget.search.hint": "搜尋此工作階段說過與做過的一切。",
    "widget.search.mode.auto": "自動",
    "widget.search.mode.fts": "關鍵字",
    "widget.search.mode.semantic": "語意",
    "widget.retry": "重試",
  },
  "zh-CN": {
    "widget.agents.title": "代理",
    "widget.channels.title": "频道",
    "widget.drives.title": "驱动",
    "widget.jobs.title": "任务",
    "widget.canvas.title": "画布",
    "widget.scratchpad.title": "暂存区",
    "widget.plugins.title": "插件",
    "widget.search.title": "搜索",
    "widget.usage.title": "用量",
    "widget.usage.empty": "尚未使用任何令牌。",
    "widget.usage.subagents": "子代理",
    "widget.openChat": "打开对话",
    "widget.start": "启动",
    "widget.stop": "停止",
    "widget.busy": "工作中",
    "widget.noModel": "无模型",
    "widget.agents.empty": "此会话没有 Creature。",
    "widget.channels.empty": "暂无频道。",
    "widget.channels.members": "{n} 位成员",
    "widget.channels.peek": "在聊天旁查看",
    "widget.channels.last": "{sender}：{text}",
    "widget.drives.empty": "此会话没有驱动。",
    "widget.jobs.empty": "当前没有运行中的任务。",
    "widget.jobs.subagent": "子代理",
    "widget.jobs.tool": "工具",
    "widget.jobs.cancelling": "停止中…",
    "widget.jobs.view": "查看",
    "widget.canvas.empty": "暂无成果。",
    "widget.focus.none": "打开某个 Creature 的对话以查看其{what}。",
    "widget.scratchpad.empty": "{name} 的暂存区是空的。",
    "widget.scratchpad.key": "键",
    "widget.scratchpad.value": "值",
    "widget.scratchpad.add": "添加",
    "widget.scratchpad.save": "保存",
    "widget.scratchpad.edit": "编辑",
    "widget.scratchpad.cancel": "取消",
    "widget.scratchpad.delete": "删除",
    "widget.scratchpad.what": "暂存区",
    "widget.plugins.empty": "没有报告任何模块。",
    "widget.plugins.what": "插件与工具",
    "widget.plugins.type.plugin": "插件",
    "widget.plugins.type.native_tool": "原生工具",
    "widget.plugins.type.tool": "工具",
    "widget.plugins.type.trigger": "触发器",
    "widget.search.placeholder": "搜索此会话的记忆…",
    "widget.search.empty": "没有匹配的结果。",
    "widget.search.hint": "搜索此会话说过与做过的一切。",
    "widget.search.mode.auto": "自动",
    "widget.search.mode.fts": "关键词",
    "widget.search.mode.semantic": "语义",
    "widget.retry": "重试",
  },
}
