/** Strings of the Workspace tab. */
export default {
  en: {
    "ws.files": "Files",
    "ws.noRoot": "This session has no working directory.",
    "ws.empty": "This folder is empty.",
    "ws.refresh": "Refresh",
    "ws.hideFiles": "Hide files",
    "ws.showFiles": "Show files",
    "ws.hideChat": "Hide chat",
    "ws.showChat": "Show chat",
    "ws.resize": "Drag to resize · double-click to reset",
    "ws.touched": "Touched by the agent",
    "ws.touchedEmpty": "The agent has not touched any files yet.",
    "ws.action.wrote": "Wrote",
    "ws.action.read": "Read",
    "ws.action.errored": "Errored",
    "ws.action.exec": "Ran",
    "ws.diff": "diff",
    "ws.rich": "Rich",
    "ws.code": "Code",
    "ws.revert": "Revert",
    "ws.save": "Save",
    "ws.pickFile": "Pick a file from the tree, or a touched file to see the agent's change.",
    "ws.treeFailed": "Could not list files: {error}",
    "ws.retry": "Retry",
    "ws.saveFailed": "Save failed: {error}",
    "ws.conflict": "This file changed on disk since you opened it. Saving overwrites that change.",
    "ws.reload": "Load disk version",
    "ws.closeDirty": "{name} has unsaved changes. Close it and discard them?",
    "ws.closeDirtyTitle": "Unsaved changes",
    "ws.discard": "Discard",
    "ws.keep": "Keep editing",
  },
  "zh-TW": {
    "ws.files": "檔案",
    "ws.noRoot": "此工作階段沒有工作目錄。",
    "ws.empty": "此資料夾是空的。",
    "ws.refresh": "重新整理",
    "ws.hideFiles": "隱藏檔案",
    "ws.showFiles": "顯示檔案",
    "ws.hideChat": "隱藏聊天",
    "ws.showChat": "顯示聊天",
    "ws.resize": "拖曳調整寬度 · 按兩下重設",
    "ws.touched": "代理動過的檔案",
    "ws.touchedEmpty": "代理尚未動過任何檔案。",
    "ws.action.wrote": "寫入",
    "ws.action.read": "讀取",
    "ws.action.errored": "出錯",
    "ws.action.exec": "執行",
    "ws.diff": "差異",
    "ws.rich": "富文字",
    "ws.code": "程式碼",
    "ws.revert": "還原",
    "ws.save": "儲存",
    "ws.pickFile": "從檔案樹選擇檔案，或選擇代理動過的檔案以查看其變更。",
    "ws.treeFailed": "無法列出檔案：{error}",
    "ws.retry": "重試",
    "ws.saveFailed": "儲存失敗：{error}",
    "ws.conflict": "此檔案在你開啟後已在磁碟上變更。儲存會覆蓋該變更。",
    "ws.reload": "載入磁碟版本",
    "ws.closeDirty": "{name} 有未儲存的變更。要關閉並捨棄嗎？",
    "ws.closeDirtyTitle": "未儲存的變更",
    "ws.discard": "捨棄",
    "ws.keep": "繼續編輯",
  },
  "zh-CN": {
    "ws.files": "文件",
    "ws.noRoot": "此会话没有工作目录。",
    "ws.empty": "此文件夹是空的。",
    "ws.refresh": "刷新",
    "ws.hideFiles": "隐藏文件",
    "ws.showFiles": "显示文件",
    "ws.hideChat": "隐藏聊天",
    "ws.showChat": "显示聊天",
    "ws.resize": "拖动调整宽度 · 双击重置",
    "ws.touched": "代理改动过的文件",
    "ws.touchedEmpty": "代理尚未改动任何文件。",
    "ws.action.wrote": "写入",
    "ws.action.read": "读取",
    "ws.action.errored": "出错",
    "ws.action.exec": "执行",
    "ws.diff": "差异",
    "ws.rich": "富文本",
    "ws.code": "代码",
    "ws.revert": "还原",
    "ws.save": "保存",
    "ws.pickFile": "从文件树选择文件，或选择代理改动过的文件以查看其变更。",
    "ws.treeFailed": "无法列出文件：{error}",
    "ws.retry": "重试",
    "ws.saveFailed": "保存失败：{error}",
    "ws.conflict": "此文件在你打开后已在磁盘上变更。保存会覆盖该变更。",
    "ws.reload": "加载磁盘版本",
    "ws.closeDirty": "{name} 有未保存的更改。要关闭并丢弃吗？",
    "ws.closeDirtyTitle": "未保存的更改",
    "ws.discard": "丢弃",
    "ws.keep": "继续编辑",
  },
}
